#!/bin/bash
#
# wpa_start
# By Niels Vanden Eynde
# 
# Script to start wpa_supplicant and dhcp.
# 
# Make sure wpa config file exists
# Create it using wpa_passphrase with your wpa settings.
#

IF=wlan0
CONF=/etc/wpa_supplicant.conf

error()
{
    echo "$1" 1>&2
    exit 1
}

check_root()
{
    if [ $EUID -ne 0 ]; then
       error "You need to be root to run this"
    fi
}

check_conf()
{
    if [ ! -f $CONF ]; then
	    error "Configuration file not found at: $CONFIG"
    fi
}

run_silent()
{
    eval "$1 >/dev/null 2>&1"
    return $?
}

stop_if_running()
{
    run_silent "killall wpa_supplicant"
    run_silent "killall dhcpcd"
}

start_wpa()
{
    local cmd='wpa_supplicant -i $IF -B -Dwext -c $CONF'
    
    echo -n "Starting wpa_supplicant... "
    if ! run_silent "$cmd"
    then
        echo "Failed"
        exit 1
    fi
    
    echo "Done"
}

start_dhcp()
{
    local cmd="dhcpcd $IF"
    
    echo -n "Starting dhcp... "
    if ! run_silent "$cmd"
    then
        echo "Failed"
        exit 1
    fi
    
    echo "Done"
}

check_root
check_conf

stop_if_running
start_wpa
start_dhcp

exit 0
